// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PterodactylDiscord;

#nullable disable

namespace PterodactylDiscord.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240827163122_AddCustomByteRules")]
    partial class AddCustomByteRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PterodactylDiscord.Models.PterodactylServer", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<ulong>("MinReceivedDelta")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MinSentDelta")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ShutdownTimer")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("PterodactylServers");
                });
#pragma warning restore 612, 618
        }
    }
}
